sidebar_alignment: 
  type: enum
  default: left
  choices: 
    - right
    - left

sidebar_show_intro: 
   type: bool 
   default: true

sidebar_show_likes:
   type: bool 
   default: true

sidebar_show_badges: 
   type: bool 
   default: true
sidebar_show_ads:
   type: bool
   default: false
sidebar_ads:
   type: list
   default: xxxx,dddd
   description: 图片地址与地址链接用,相隔
